use AI_BoxPush;
-- 使用本数据库
DROP TABLE IF EXISTS `game1`;
CREATE TABLE IF NOT EXISTS `game1` (
`type` varchar(30) not null,
`x` int not null,
`y` int not null,
primary key (`x`,`y`)
);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,0);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',5,0);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',6,0);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',7,0);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,0);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,1);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,1);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,2);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',5,2);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,2);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',2,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',3,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',7,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',9,3);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',2,4);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',5,4);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',7,4);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',9,4);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',0,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',1,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',2,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',6,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',7,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',9,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',13,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',14,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',15,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',16,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',17,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',18,5);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',0,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',6,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',7,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',9,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',10,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',11,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',12,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',13,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',16,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',17,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',18,6);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',0,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',2,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('$',5,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',16,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',17,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',18,7);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',0,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',1,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',2,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',3,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',6,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',7,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',10,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('@',11,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',12,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',13,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',16,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('.',17,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',18,8);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',10,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',11,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',12,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',13,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',14,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',15,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',16,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',17,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',18,9);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',4,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',5,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',6,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',7,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',8,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',9,10);
INSERT INTO `game1` (`type`,`x`,`y`) VALUES ('#',10,10);

insert IGNORE into info (gameTable) values ('game1');
