use AI_BoxPush;
-- 使用本数据库
DROP TABLE IF EXISTS `game5`;
CREATE TABLE IF NOT EXISTS `game5` (
`type` varchar(30) not null,
`x` int not null,
`y` int not null,
primary key (`x`,`y`)
);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,0);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',9,0);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,0);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',11,0);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,0);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',13,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',14,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',16,1);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',11,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',13,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',16,2);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,3);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',14,3);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',16,3);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',0,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',1,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',2,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',3,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',4,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',5,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',6,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',7,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',11,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',16,4);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',0,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',1,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',2,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',3,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',4,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',7,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',10,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',13,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',14,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',16,5);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',0,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',1,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',2,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',3,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',4,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',9,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',11,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',12,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',14,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,6);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',0,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',1,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',2,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',3,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('.',4,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',7,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',9,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',12,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('@',14,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,7);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',0,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',1,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',2,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',3,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',4,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',5,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',6,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',7,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',11,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',14,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,8);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,9);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',10,9);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('$',12,9);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,9);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',8,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',9,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',13,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,10);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,11);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,11);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',10,12);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',11,12);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',12,12);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',13,12);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',14,12);
INSERT INTO `game5` (`type`,`x`,`y`) VALUES ('#',15,12);

insert IGNORE into info (gameTable) values ('game5');
