use AI_BoxPush;
-- 使用本数据库
DROP TABLE IF EXISTS `test`;
CREATE TABLE IF NOT EXISTS `test` (
`type` varchar(30) not null,
`x` int not null,
`y` int not null,
primary key (`x`,`y`)
);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',1,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',2,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',3,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',4,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',5,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',6,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',7,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',8,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',9,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',10,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',11,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,0);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,1);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,1);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,2);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',6,2);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,2);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,3);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('@',6,3);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,3);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,4);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,4);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',3,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',4,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',5,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',6,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',7,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',8,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,5);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,6);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,6);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',3,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',4,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',5,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',6,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',7,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('$',8,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,7);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',1,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',2,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',3,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',4,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',5,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',6,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',7,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',8,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',9,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',10,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',11,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,8);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',1,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',2,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',3,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',4,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',5,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',6,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',7,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',8,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',9,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',10,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('.',11,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,9);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',0,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',1,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',2,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',3,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',4,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',5,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',6,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',7,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',8,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',9,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',10,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',11,10);
INSERT INTO `test` (`type`,`x`,`y`) VALUES ('#',12,10);

insert IGNORE into info (gameTable) values ('test');
